# Generated by Django 4.2.16 on 2025-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0002_diarymodel_productivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarymodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
