# Generated by Django 4.2.16 on 2025-10-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0003_alter_diarymodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarymodel",
            name="image_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Diary Image",
            ),
        ),
    ]

