# Generated by Django 4.2.16 on 2025-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_diarymodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymodel',
            name='temp_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='temp_Image'),
        ),
    ]
