# Generated by Django 4.2.16 on 2025-10-19 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0005_diarymodel_temp_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymodel',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
