# Generated by Django 4.2.16 on 2025-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_alter_diarymodel_options_diarymodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymodel',
            name='final_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
